version: '3.3'
services:
  postgres:
    build: 
      context: .
    image: postgres:14-alpine
    container_name: ${PG_CONTAINER_NAME}
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA:${PGDATA}
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
  backend:
    container_name: backend
    build: 
      context: .
      dockerfile: ./Dockerfile
    image: backend-library:latest
    ports:
      - "49170:8080"
    links:
      - postgres
    volumes:
      - /node_modules
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend:
    name: hastega-net
    external: true