version: '3.3'
services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_PASS}
      - PGDATA=${PGDATA}
    volumes:
      - ./ddls:/docker-entrypoint-initdb.d
      - ./data:/var/lib/postgresql/data
    networks:
      - backend
    restart: always
  backend:
    build: ./
    image: backend-library:latest
    ports:
      - "49170:8080"
    volumes:
      - /node_modules
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend: