version: '3.3'
services:
  postgres:
    build: 
      context: .
    image: postgres:14-alpine
    container_name: ${PG_CONTAINER_NAME}
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
      - PGDATA:${PGDATA}
    volumes:
      - ./ddls:/docker-entrypoint-initdb.d
      - hastega-volume:/data/postgres-hastega
    networks:
      - backend
    restart: always
  backend:
    build: 
      context: .
    image: backend-library:latest
    ports:
      - "49170:8080"
    volumes:
      - /node_modules
    depends_on:
      - postgres
    networks:
      - backend
networks:
  backend:
    name: shared-network
volumes:
    hastega-volume:
      external: true